version: 2.0.{build}

skip_branch_with_pr: true

image: Visual Studio 2017

before_build:
- ps: dotnet restore

build:
  publish_wap: true
  verbosity: minimal

after_build:
- ps: .\Test.ps1 -Configuration Release
- ps: .\Package.ps1 -Configuration Release

test: off

artifacts:
- path: AlertRoster.Web.zip
  type: WebDeployPackage